services:
  redis:
    image: redis:alpine
    ports:
      - "6378:6379"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    image: minhmatmong/librarails:latest
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: "http://127.0.0.1"
      PORT: 3000
      MAIL_ADDRESS: ${mail_address}
      MAIL_PORT: ${mail_port}
      MAIL_USERNAME: ${mail_username}
      MAIL_PASSWORD: ${mail_password}
      REDIS_URL: "redis://redis:6379/1"
    entrypoint: ["/usr/bin/entrypoint.sh"]
    command: ["rails", "s", "-b", "0.0.0.0"]
    develop:
      watch:
        - path: ./app
          target: /app/app
          action: sync

  tailwind:
    image: minhmatmong/librarails:latest
    command: rails tailwindcss:watch
    stdin_open: true
    volumes:
      - "./:/app"


volumes:
  mysql_data:
